<a href="https://colab.research.google.com/github/ANJALICHAMOLI/Deep-Learning/blob/main/hyperpara_tuning_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pima-indians-diabetes-database' dataset.
Path to dataset files: /kaggle/input/pima-indians-diabetes-database

In [ ]:
import os

In [ ]:
csv_path = os.path.join(path, "diabetes.csv")

df = pd.read_csv(csv_path)

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
#to check what affects out come more amoug the columns
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
x=df.iloc[ :,0:8]
y= df.iloc[ : ,-1]

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 48.1 KB

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X=scaler.fit_transform(x)

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [ ]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation = 'sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs =100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.6645 - loss: 0.6267 - val_accuracy: 0.7273 - val_loss: 0.5653
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7101 - loss: 0.5782 - val_accuracy: 0.7662 - val_loss: 0.5322
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7313 - loss: 0.5454 - val_accuracy: 0.7727 - val_loss: 0.5087
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7573 - loss: 0.5226 - val_accuracy: 0.8052 - val_loss: 0.4910
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.5059 - val_accuracy: 0.8247 - val_loss: 0.4788
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7704 - loss: 0.4933 - val_accuracy: 0.8312 - val_loss: 0.4701
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4836 - val_accuracy: 0.8377 - val_loss: 0.4639
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4759 - val_accuracy: 0.8182 - val_loss: 0.4593
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4702 - val_accuracy: 0.8247 - val_loss: 0.4555
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4658 - val_accuracy: 0.8312 - val_loss: 0.4539
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4620 - val_accuracy: 0.8377 - val_loss: 0.4519
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4586 - val_accuracy: 0.8377 - val_loss: 0.4517
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4563 - val_accuracy: 0.8377 - val_loss: 0.4503
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4545 - val_accuracy: 0.8312 - val_loss: 0.4509
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4531 - val_accuracy: 0.8182 - val_loss: 0.4501
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4508 - val_accuracy: 0.8247 - val_loss: 0.4507
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4495 - val_accuracy: 0.8247 - val_loss: 0.4505
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4480 - val_accuracy: 0.8247 - val_loss: 0.4495
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4470 - val_accuracy: 0.8247 - val_loss: 0.4500
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4456 - val_accuracy: 0.8182 - val_loss: 0.4496
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4450 - val_accuracy: 0.8182 - val_loss: 0.4490
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4439 - val_accuracy: 0.8182 - val_loss: 0.4493
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4433 - val_accuracy: 0.8182 - val_loss: 0.4496
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4421 - val_accuracy: 0.8182 - val_loss: 0.4494
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4413 - val_accuracy: 0.8182 - val_loss: 0.4496
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4408 - val_accuracy: 0.8182 - val_loss: 0.4492
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4403 - val_accuracy: 0.8052 - val_loss: 0.4499
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4402 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4395 - val_accuracy: 0.8247 - val_loss: 0.4501
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4385 - val_accuracy: 0.8247 - val_loss: 0.4503
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4381 - val_accuracy: 0.8182 - val_loss: 0.4492
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4378 - val_accuracy: 0.8182 - val_loss: 0.4490
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4373 - val_accuracy: 0.8182 - val_loss: 0.4481
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7915 - loss: 0.4366 - val_accuracy: 0.8182 - val_loss: 0.4477
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7866 - loss: 0.4363 - val_accuracy: 0.8117 - val_loss: 0.4470
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4359 - val_accuracy: 0.8117 - val_loss: 0.4475
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4352 - val_accuracy: 0.8117 - val_loss: 0.4484
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7866 - loss: 0.4350 - val_accuracy: 0.8117 - val_loss: 0.4495
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7883 - loss: 0.4345 - val_accuracy: 0.8117 - val_loss: 0.4490
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4340 - val_accuracy: 0.8117 - val_loss: 0.4493
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4336 - val_accuracy: 0.8117 - val_loss: 0.4500
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4333 - val_accuracy: 0.8052 - val_loss: 0.4494
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4322 - val_accuracy: 0.8052 - val_loss: 0.4507
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4324 - val_accuracy: 0.8117 - val_loss: 0.4514
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4308 - val_accuracy: 0.8052 - val_loss: 0.4510
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4304 - val_accuracy: 0.8117 - val_loss: 0.4507
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4303 - val_accuracy: 0.7987 - val_loss: 0.4505
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4303 - val_accuracy: 0.7987 - val_loss: 0.4512
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4296 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4290 - val_accuracy: 0.8052 - val_loss: 0.4506
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4281 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4283 - val_accuracy: 0.8052 - val_loss: 0.4497
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4274 - val_accuracy: 0.7987 - val_loss: 0.4503
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4269 - val_accuracy: 0.8117 - val_loss: 0.4500
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4263 - val_accuracy: 0.8117 - val_loss: 0.4501
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4260 - val_accuracy: 0.8117 - val_loss: 0.4508
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4262 - val_accuracy: 0.7987 - val_loss: 0.4506
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4252 - val_accuracy: 0.8117 - val_loss: 0.4507
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.7987 - val_loss: 0.4512
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4246 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4244 - val_accuracy: 0.8052 - val_loss: 0.4519
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4247 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4232 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4226 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4222 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4507
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4214 - val_accuracy: 0.7987 - val_loss: 0.4514
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4211 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4212 - val_accuracy: 0.7987 - val_loss: 0.4502
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4201 - val_accuracy: 0.7987 - val_loss: 0.4506
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4201 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4198 - val_accuracy: 0.7987 - val_loss: 0.4504
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4197 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4190 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4186 - val_accuracy: 0.8052 - val_loss: 0.4507
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4191 - val_accuracy: 0.7987 - val_loss: 0.4496
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4185 - val_accuracy: 0.8117 - val_loss: 0.4512
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4179 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4178 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4171 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4170 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4160 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4158 - val_accuracy: 0.8052 - val_loss: 0.4530
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4157 - val_accuracy: 0.8052 - val_loss: 0.4526
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4152 - val_accuracy: 0.8052 - val_loss: 0.4518
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4151 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4152 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4148 - val_accuracy: 0.8117 - val_loss: 0.4514
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4141 - val_accuracy: 0.8052 - val_loss: 0.4526
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4139 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4137 - val_accuracy: 0.7987 - val_loss: 0.4520
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4135 - val_accuracy: 0.7987 - val_loss: 0.4524
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4133 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4127 - val_accuracy: 0.7987 - val_loss: 0.4532
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4127 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4121 - val_accuracy: 0.7987 - val_loss: 0.4536

# hyperparameter tuning in kears for best results

steps:-


1. how to select appropriate optimizer
2. no o fnodes in layer
3. how to select no of layers
4. all in all one model at last

In [ ]:
!pip install keras-tuner -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 7.2 MB/s eta 0:00:00

In [ ]:
import kerastuner as kt

/tmp/ipykernel_59133/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

#for optimizer

In [ ]:
from keras.src.losses import binary_crossentropy
def build_model_optimizer(hp):
  model1 = Sequential()

  model1.add(Dense(32,activation='relu',input_dim=8))
  model1.add(Dense(1,activation = 'sigmoid'))

  optimizer = hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])

  model1.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])

  return model1

In [ ]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5 ,directory='my_dir',
                        project_name = 'tuning optimizers',
                        overwrite=True)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 10s

In [ ]:
tuner.results_summary()

Results summary
Results in my_dir/tuning optimizers
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: sgd
Score: 0.7792207598686218

Trial 2 summary
Hyperparameters:
optimizer: adam
Score: 0.7662337422370911

Trial 0 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7467532753944397

Trial 1 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5259740352630615

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model1=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model1.fit(x_train,y_train,batch_size=32,epochs =100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6922 - loss: 0.6302 - val_accuracy: 0.7857 - val_loss: 0.5737
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.6182 - val_accuracy: 0.7922 - val_loss: 0.5635
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.6062 - val_accuracy: 0.7922 - val_loss: 0.5547
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5961 - val_accuracy: 0.7857 - val_loss: 0.5467
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5869 - val_accuracy: 0.7857 - val_loss: 0.5396
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5785 - val_accuracy: 0.7857 - val_loss: 0.5331
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5704 - val_accuracy: 0.7792 - val_loss: 0.5268
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5632 - val_accuracy: 0.7727 - val_loss: 0.5209
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5562 - val_accuracy: 0.7792 - val_loss: 0.5159
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5504 - val_accuracy: 0.7922 - val_loss: 0.5110
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5447 - val_accuracy: 0.7987 - val_loss: 0.5064
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5391 - val_accuracy: 0.8052 - val_loss: 0.5023
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5339 - val_accuracy: 0.8052 - val_loss: 0.4984
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5293 - val_accuracy: 0.8052 - val_loss: 0.4948
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5249 - val_accuracy: 0.8182 - val_loss: 0.4912
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.5207 - val_accuracy: 0.8117 - val_loss: 0.4884
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5170 - val_accuracy: 0.8182 - val_loss: 0.4857
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5135 - val_accuracy: 0.8182 - val_loss: 0.4833
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5103 - val_accuracy: 0.8117 - val_loss: 0.4810
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5075 - val_accuracy: 0.8117 - val_loss: 0.4788
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5048 - val_accuracy: 0.8117 - val_loss: 0.4765
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5021 - val_accuracy: 0.8117 - val_loss: 0.4744
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4996 - val_accuracy: 0.8117 - val_loss: 0.4724
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4973 - val_accuracy: 0.8117 - val_loss: 0.4710
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4951 - val_accuracy: 0.8117 - val_loss: 0.4694
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4930 - val_accuracy: 0.8117 - val_loss: 0.4678
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4911 - val_accuracy: 0.8117 - val_loss: 0.4665
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4895 - val_accuracy: 0.8052 - val_loss: 0.4652
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4876 - val_accuracy: 0.8052 - val_loss: 0.4641
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4860 - val_accuracy: 0.8052 - val_loss: 0.4630
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4844 - val_accuracy: 0.8052 - val_loss: 0.4619
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4829 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4817 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4808 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4793 - val_accuracy: 0.7922 - val_loss: 0.4592
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7736 - loss: 0.4783 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7736 - loss: 0.4773 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7704 - loss: 0.4763 - val_accuracy: 0.7922 - val_loss: 0.4574
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7720 - loss: 0.4755 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4747 - val_accuracy: 0.7922 - val_loss: 0.4562
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4739 - val_accuracy: 0.7922 - val_loss: 0.4557
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4732 - val_accuracy: 0.7922 - val_loss: 0.4553
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4725 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4717 - val_accuracy: 0.7987 - val_loss: 0.4542
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4711 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4706 - val_accuracy: 0.7987 - val_loss: 0.4535
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4701 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4696 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4691 - val_accuracy: 0.7987 - val_loss: 0.4526
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4685 - val_accuracy: 0.7987 - val_loss: 0.4527
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4680 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4675 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4670 - val_accuracy: 0.7922 - val_loss: 0.4527
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4666 - val_accuracy: 0.7922 - val_loss: 0.4525
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4663 - val_accuracy: 0.7922 - val_loss: 0.4521
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4658 - val_accuracy: 0.7922 - val_loss: 0.4518
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4654 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4650 - val_accuracy: 0.7922 - val_loss: 0.4516
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4647 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4643 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4641 - val_accuracy: 0.7922 - val_loss: 0.4511
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4638 - val_accuracy: 0.7922 - val_loss: 0.4507
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4633 - val_accuracy: 0.7922 - val_loss: 0.4507
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4632 - val_accuracy: 0.7922 - val_loss: 0.4504
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4627 - val_accuracy: 0.7922 - val_loss: 0.4502
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4624 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4623 - val_accuracy: 0.7922 - val_loss: 0.4507
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4620 - val_accuracy: 0.7922 - val_loss: 0.4511
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4618 - val_accuracy: 0.7922 - val_loss: 0.4505
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4615 - val_accuracy: 0.7922 - val_loss: 0.4501
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4612 - val_accuracy: 0.7922 - val_loss: 0.4499
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4608 - val_accuracy: 0.7922 - val_loss: 0.4496
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4608 - val_accuracy: 0.7922 - val_loss: 0.4497
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4604 - val_accuracy: 0.7922 - val_loss: 0.4500
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4603 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4599 - val_accuracy: 0.7987 - val_loss: 0.4494
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4597 - val_accuracy: 0.7987 - val_loss: 0.4493
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4595 - val_accuracy: 0.8052 - val_loss: 0.4490
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4592 - val_accuracy: 0.8052 - val_loss: 0.4486
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4590 - val_accuracy: 0.8052 - val_loss: 0.4485
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4588 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4586 - val_accuracy: 0.7987 - val_loss: 0.4483
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4584 - val_accuracy: 0.8052 - val_loss: 0.4485
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4484
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4580 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4578 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4577 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4573 - val_accuracy: 0.7922 - val_loss: 0.4485
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4573 - val_accuracy: 0.7922 - val_loss: 0.4483
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4569 - val_accuracy: 0.7922 - val_loss: 0.4480
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4568 - val_accuracy: 0.7922 - val_loss: 0.4481
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4566 - val_accuracy: 0.7987 - val_loss: 0.4479
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4565 - val_accuracy: 0.7922 - val_loss: 0.4479
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4563 - val_accuracy: 0.7922 - val_loss: 0.4478
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4562 - val_accuracy: 0.7922 - val_loss: 0.4479
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4559 - val_accuracy: 0.7987 - val_loss: 0.4479
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4558 - val_accuracy: 0.7987 - val_loss: 0.4479
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4556 - val_accuracy: 0.7987 - val_loss: 0.4478
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4554 - val_accuracy: 0.7987 - val_loss: 0.4479
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4553 - val_accuracy: 0.7922 - val_loss: 0.4481

#for no of nurons

In [ ]:
def build_model_nurons(hp):

  model2 =Sequential()

  units =hp.Int('units',min_value=8,max_value=128,step=8) #lower_limit,upper_limit,step_size

  model2.add(Dense(units=units,activation='relu',input_dim=8))
  model2.add(Dense(1,activation='sigmoid'))

  model2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model2

In [ ]:
tuner2=kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='my_dir',
                        project_name = 'tuning nurons',
                        overwrite=True)

In [ ]:
tuner2.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 15s

In [ ]:
tuner2.results_summary(num_trials=5)  # Match your max_trials

Results summary
Results in my_dir/tuning nurons
Showing 5 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
units: 128
Score: 0.8051947951316833

Trial 2 summary
Hyperparameters:
units: 72
Score: 0.7922077775001526

Trial 1 summary
Hyperparameters:
units: 64
Score: 0.7857142686843872

Trial 3 summary
Hyperparameters:
units: 112
Score: 0.7857142686843872

Trial 4 summary
Hyperparameters:
units: 40
Score: 0.7792207598686218

In [ ]:
tuner2.get_best_hyperparameters()[0].values

{'units': 128}

In [ ]:
model2=tuner2.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model2.fit(x_train, y_train, batch_size=32, epochs=100,
           validation_data=(x_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.8306 - loss: 0.3817 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8322 - loss: 0.3811 - val_accuracy: 0.8117 - val_loss: 0.4657
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3810 - val_accuracy: 0.8117 - val_loss: 0.4655
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3803 - val_accuracy: 0.8117 - val_loss: 0.4638
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3814 - val_accuracy: 0.8052 - val_loss: 0.4659
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3789 - val_accuracy: 0.8052 - val_loss: 0.4646
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3788 - val_accuracy: 0.8052 - val_loss: 0.4651
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3777 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3776 - val_accuracy: 0.8052 - val_loss: 0.4704
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3769 - val_accuracy: 0.8052 - val_loss: 0.4718
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3773 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3788 - val_accuracy: 0.8117 - val_loss: 0.4611
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3758 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3748 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3740 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3745 - val_accuracy: 0.8052 - val_loss: 0.4685
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3737 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3716 - val_accuracy: 0.8052 - val_loss: 0.4672
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3718 - val_accuracy: 0.8052 - val_loss: 0.4724
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3722 - val_accuracy: 0.7987 - val_loss: 0.4720
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3711 - val_accuracy: 0.8052 - val_loss: 0.4721
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3702 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3706 - val_accuracy: 0.8052 - val_loss: 0.4676
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3704 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3701 - val_accuracy: 0.7987 - val_loss: 0.4722
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3685 - val_accuracy: 0.8052 - val_loss: 0.4707
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8371 - loss: 0.3691 - val_accuracy: 0.8052 - val_loss: 0.4746
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8420 - loss: 0.3689 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.3683 - val_accuracy: 0.7922 - val_loss: 0.4726
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8388 - loss: 0.3664 - val_accuracy: 0.8052 - val_loss: 0.4722
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3651 - val_accuracy: 0.8052 - val_loss: 0.4698
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3665 - val_accuracy: 0.8052 - val_loss: 0.4736
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8453 - loss: 0.3653 - val_accuracy: 0.8052 - val_loss: 0.4744
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3674 - val_accuracy: 0.7987 - val_loss: 0.4765
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8355 - loss: 0.3636 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8453 - loss: 0.3640 - val_accuracy: 0.8052 - val_loss: 0.4693
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8436 - loss: 0.3640 - val_accuracy: 0.8052 - val_loss: 0.4694
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8420 - loss: 0.3627 - val_accuracy: 0.8052 - val_loss: 0.4750
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3636 - val_accuracy: 0.8117 - val_loss: 0.4685
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3621 - val_accuracy: 0.8052 - val_loss: 0.4720
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3601 - val_accuracy: 0.7987 - val_loss: 0.4732
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3631 - val_accuracy: 0.7987 - val_loss: 0.4733
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3605 - val_accuracy: 0.8052 - val_loss: 0.4741
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3625 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3601 - val_accuracy: 0.7987 - val_loss: 0.4757
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3605 - val_accuracy: 0.7987 - val_loss: 0.4800
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3584 - val_accuracy: 0.8052 - val_loss: 0.4779
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3576 - val_accuracy: 0.8052 - val_loss: 0.4778
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3584 - val_accuracy: 0.7987 - val_loss: 0.4792
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3563 - val_accuracy: 0.8052 - val_loss: 0.4778
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3571 - val_accuracy: 0.8052 - val_loss: 0.4800
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3561 - val_accuracy: 0.8052 - val_loss: 0.4758
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3543 - val_accuracy: 0.8052 - val_loss: 0.4780
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3543 - val_accuracy: 0.8052 - val_loss: 0.4808
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3569 - val_accuracy: 0.7987 - val_loss: 0.4799
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3542 - val_accuracy: 0.8052 - val_loss: 0.4759
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3542 - val_accuracy: 0.8052 - val_loss: 0.4783
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3529 - val_accuracy: 0.8052 - val_loss: 0.4796
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3543 - val_accuracy: 0.8052 - val_loss: 0.4809
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3532 - val_accuracy: 0.8052 - val_loss: 0.4799
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3526 - val_accuracy: 0.8052 - val_loss: 0.4846
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3506 - val_accuracy: 0.8052 - val_loss: 0.4806
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3513 - val_accuracy: 0.8052 - val_loss: 0.4787
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3509 - val_accuracy: 0.8052 - val_loss: 0.4785
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3501 - val_accuracy: 0.8052 - val_loss: 0.4767
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3499 - val_accuracy: 0.8117 - val_loss: 0.4749
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3489 - val_accuracy: 0.8052 - val_loss: 0.4750
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8567 - loss: 0.3498 - val_accuracy: 0.8052 - val_loss: 0.4752
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3488 - val_accuracy: 0.7987 - val_loss: 0.4783
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3516 - val_accuracy: 0.8117 - val_loss: 0.4723
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3501 - val_accuracy: 0.8052 - val_loss: 0.4739
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3484 - val_accuracy: 0.8052 - val_loss: 0.4771
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3481 - val_accuracy: 0.7922 - val_loss: 0.4827
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3457 - val_accuracy: 0.8052 - val_loss: 0.4740
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3461 - val_accuracy: 0.8052 - val_loss: 0.4816
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3444 - val_accuracy: 0.8052 - val_loss: 0.4792
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3452 - val_accuracy: 0.8052 - val_loss: 0.4850
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3448 - val_accuracy: 0.7987 - val_loss: 0.4811
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3442 - val_accuracy: 0.8052 - val_loss: 0.4816
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3450 - val_accuracy: 0.8117 - val_loss: 0.4847
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.3417 - val_accuracy: 0.7987 - val_loss: 0.4866
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3428 - val_accuracy: 0.8052 - val_loss: 0.4862
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3430 - val_accuracy: 0.7922 - val_loss: 0.4795
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3427 - val_accuracy: 0.8052 - val_loss: 0.4795
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8599 - loss: 0.3424 - val_accuracy: 0.8052 - val_loss: 0.4777
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3411 - val_accuracy: 0.8117 - val_loss: 0.4811
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3399 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3387 - val_accuracy: 0.8052 - val_loss: 0.4790
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3399 - val_accuracy: 0.7922 - val_loss: 0.4858
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3406 - val_accuracy: 0.7987 - val_loss: 0.4839
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3389 - val_accuracy: 0.8052 - val_loss: 0.4772
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3379 - val_accuracy: 0.7987 - val_loss: 0.4823
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3366 - val_accuracy: 0.8052 - val_loss: 0.4813
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3373 - val_accuracy: 0.7987 - val_loss: 0.4854
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3365 - val_accuracy: 0.7922 - val_loss: 0.4879
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3352 - val_accuracy: 0.7987 - val_loss: 0.4873
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3349 - val_accuracy: 0.7987 - val_loss: 0.4849
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3348 - val_accuracy: 0.7987 - val_loss: 0.4893
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3341 - val_accuracy: 0.7987 - val_loss: 0.4904
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3345 - val_accuracy: 0.7987 - val_loss: 0.4894

# for no of layers

In [ ]:
def build_model_layers(hp):

  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):

    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [ ]:
tuner3 = kt.RandomSearch(build_model_layers,
                         objective ='val_accuracy',
                         max_trials=3,
                         directory='my dir',
                         project_name='tuning layers',
                         overwrite=True)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner3.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 20s

In [ ]:
tuner3.get_best_hyperparameters()[0].values

{'num_layers': 8}

In [ ]:
model3= tuner3.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model3.fit(x_train,y_train,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - accuracy: 0.7997 - loss: 0.4349 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4107 - val_accuracy: 0.7922 - val_loss: 0.4895
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.4007 - val_accuracy: 0.7727 - val_loss: 0.4874
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8257 - loss: 0.3872 - val_accuracy: 0.7987 - val_loss: 0.4849
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8469 - loss: 0.3612 - val_accuracy: 0.7922 - val_loss: 0.5081
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8388 - loss: 0.3535 - val_accuracy: 0.7662 - val_loss: 0.5421
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3510 - val_accuracy: 0.7857 - val_loss: 0.5133
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3160 - val_accuracy: 0.7727 - val_loss: 0.5857
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8746 - loss: 0.3038 - val_accuracy: 0.7857 - val_loss: 0.5959
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8925 - loss: 0.2844 - val_accuracy: 0.7792 - val_loss: 0.6238
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8909 - loss: 0.2828 - val_accuracy: 0.7532 - val_loss: 0.6828
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9055 - loss: 0.2599 - val_accuracy: 0.7403 - val_loss: 0.6581
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8925 - loss: 0.2704 - val_accuracy: 0.7532 - val_loss: 0.6621
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.3092 - val_accuracy: 0.7013 - val_loss: 0.6075
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9072 - loss: 0.2460 - val_accuracy: 0.7792 - val_loss: 0.7095
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9300 - loss: 0.1940 - val_accuracy: 0.7078 - val_loss: 0.8250
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9202 - loss: 0.1988 - val_accuracy: 0.7662 - val_loss: 0.8315
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9218 - loss: 0.1975 - val_accuracy: 0.7792 - val_loss: 0.7539
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9300 - loss: 0.1819 - val_accuracy: 0.7338 - val_loss: 0.8483
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9316 - loss: 0.1793 - val_accuracy: 0.7273 - val_loss: 1.0371
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9202 - loss: 0.2122 - val_accuracy: 0.7597 - val_loss: 0.8391
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9186 - loss: 0.2155 - val_accuracy: 0.7792 - val_loss: 0.7449
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9446 - loss: 0.1602 - val_accuracy: 0.7468 - val_loss: 0.9223
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9463 - loss: 0.1450 - val_accuracy: 0.7208 - val_loss: 1.1257
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9414 - loss: 0.1383 - val_accuracy: 0.7208 - val_loss: 1.0679
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9479 - loss: 0.1333 - val_accuracy: 0.7273 - val_loss: 1.0859
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9430 - loss: 0.1560 - val_accuracy: 0.7013 - val_loss: 1.0800
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9495 - loss: 0.1381 - val_accuracy: 0.7208 - val_loss: 1.1960
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9756 - loss: 0.0733 - val_accuracy: 0.7208 - val_loss: 1.3701
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0643 - val_accuracy: 0.7078 - val_loss: 1.4154
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9723 - loss: 0.0757 - val_accuracy: 0.7403 - val_loss: 1.3632
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.0862 - val_accuracy: 0.7078 - val_loss: 1.2857
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9642 - loss: 0.0901 - val_accuracy: 0.7078 - val_loss: 1.5293
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9625 - loss: 0.1068 - val_accuracy: 0.7078 - val_loss: 1.3685
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9593 - loss: 0.0890 - val_accuracy: 0.7338 - val_loss: 1.4565
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.0707 - val_accuracy: 0.7208 - val_loss: 1.6469
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9218 - loss: 0.2031 - val_accuracy: 0.7662 - val_loss: 0.9637
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1414 - val_accuracy: 0.7273 - val_loss: 1.0955
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0555 - val_accuracy: 0.7208 - val_loss: 1.7751
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0500 - val_accuracy: 0.7403 - val_loss: 1.8556
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0427 - val_accuracy: 0.7143 - val_loss: 1.7294
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0526 - val_accuracy: 0.7403 - val_loss: 2.0745
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9723 - loss: 0.0717 - val_accuracy: 0.7143 - val_loss: 1.6739
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9739 - loss: 0.0719 - val_accuracy: 0.7208 - val_loss: 1.4742
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0430 - val_accuracy: 0.7208 - val_loss: 1.7469
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9886 - loss: 0.0462 - val_accuracy: 0.7273 - val_loss: 1.8301
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9625 - loss: 0.1170 - val_accuracy: 0.7403 - val_loss: 1.0749
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9691 - loss: 0.1078 - val_accuracy: 0.7273 - val_loss: 1.1733
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9870 - loss: 0.0434 - val_accuracy: 0.7338 - val_loss: 1.4371
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9853 - loss: 0.0412 - val_accuracy: 0.7208 - val_loss: 1.7223
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9919 - loss: 0.0305 - val_accuracy: 0.7273 - val_loss: 1.9378
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9951 - loss: 0.0118 - val_accuracy: 0.7143 - val_loss: 1.9905
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.7208 - val_loss: 2.2848
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9967 - loss: 0.0074 - val_accuracy: 0.7208 - val_loss: 2.5309
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9902 - loss: 0.0311 - val_accuracy: 0.7273 - val_loss: 2.2532
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9772 - loss: 0.0706 - val_accuracy: 0.7208 - val_loss: 1.7876
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0549 - val_accuracy: 0.7468 - val_loss: 1.8132
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0300 - val_accuracy: 0.7403 - val_loss: 2.0007
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0326 - val_accuracy: 0.7403 - val_loss: 2.1428
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0308 - val_accuracy: 0.7143 - val_loss: 2.2368
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9691 - loss: 0.0988 - val_accuracy: 0.7468 - val_loss: 1.6050
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0637 - val_accuracy: 0.7532 - val_loss: 1.9108
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9739 - loss: 0.1093 - val_accuracy: 0.7532 - val_loss: 1.4252
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.0936 - val_accuracy: 0.7338 - val_loss: 1.4203
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0576 - val_accuracy: 0.7013 - val_loss: 1.3752
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9837 - loss: 0.0553 - val_accuracy: 0.7532 - val_loss: 1.6275
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0632 - val_accuracy: 0.7532 - val_loss: 1.4634
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0375 - val_accuracy: 0.7338 - val_loss: 1.5086
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0243 - val_accuracy: 0.7273 - val_loss: 1.6596
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0131 - val_accuracy: 0.7403 - val_loss: 2.1551
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9837 - loss: 0.0614 - val_accuracy: 0.7468 - val_loss: 1.5507
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0404 - val_accuracy: 0.7338 - val_loss: 1.4270
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0231 - val_accuracy: 0.7208 - val_loss: 1.6728
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0181 - val_accuracy: 0.7338 - val_loss: 1.9675
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0143 - val_accuracy: 0.7273 - val_loss: 2.0197
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0489 - val_accuracy: 0.7143 - val_loss: 1.6917
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9674 - loss: 0.1157 - val_accuracy: 0.7597 - val_loss: 1.1095
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9772 - loss: 0.0708 - val_accuracy: 0.7468 - val_loss: 1.3431
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9919 - loss: 0.0424 - val_accuracy: 0.7273 - val_loss: 1.6071
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0260 - val_accuracy: 0.7468 - val_loss: 1.9350
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9951 - loss: 0.0211 - val_accuracy: 0.7468 - val_loss: 1.9125
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0545 - val_accuracy: 0.7338 - val_loss: 1.3023
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9691 - loss: 0.1070 - val_accuracy: 0.7273 - val_loss: 1.2710
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0409 - val_accuracy: 0.7078 - val_loss: 1.5199
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0166 - val_accuracy: 0.7273 - val_loss: 1.9117
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0066 - val_accuracy: 0.7338 - val_loss: 2.1443
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.7273 - val_loss: 2.3646
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.7338 - val_loss: 2.6419
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 7.9050e-04 - val_accuracy: 0.7273 - val_loss: 2.7958
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7208 - val_loss: 2.9291
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0043 - val_accuracy: 0.7273 - val_loss: 2.9673
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0048 - val_accuracy: 0.7273 - val_loss: 2.7662
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0048 - val_accuracy: 0.7208 - val_loss: 2.7750
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0020 - val_accuracy: 0.7078 - val_loss: 2.8726

# getting multiple things as once

In [ ]:
def build_model_all(hp):
    model = Sequential()

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        if i == 0:
            model.add(Dense(
                hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation_' + str(i), values=['relu', 'tanh', 'sigmoid']),
                input_dim=8  # only needed on first layer
            ))
            model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
        else:
            model.add(Dense(
                hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
            ))
            model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))


    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [ ]:
tuner4= kt.RandomSearch(build_model_all,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='my dir',
                        project_name='tuning all paras')

Reloading Tuner from my dir/tuning all paras/tuner0.json

In [ ]:
tuner4.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [ ]:
tuner4.get_best_hyperparameters()[0].values

{'num_layers': 6,
 'units_0': 96,
 'activation_0': 'tanh',
 'optimizer': 'adam',
 'units_1': 72,
 'activation_1': 'sigmoid',
 'units_2': 32,
 'activation_2': 'tanh',
 'units_3': 112,
 'activation_3': 'relu',
 'units_4': 104,
 'activation_4': 'relu',
 'units_5': 112,
 'activation_5': 'tanh'}

In [ ]:
model4=tuner4.get_best_models(num_models=1)[0]

In [ ]:
model.fit(x_train,y_train,epochs=200,validation_data=(x_test,y_test))

Epoch 1/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8111 - loss: 0.4255 - val_accuracy: 0.7857 - val_loss: 0.4556
Epoch 2/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4248 - val_accuracy: 0.7922 - val_loss: 0.4547
Epoch 3/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4245 - val_accuracy: 0.7922 - val_loss: 0.4553
Epoch 4/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4243 - val_accuracy: 0.7922 - val_loss: 0.4552
Epoch 5/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4244 - val_accuracy: 0.7922 - val_loss: 0.4554
Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4237 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4233 - val_accuracy: 0.7922 - val_loss: 0.4547
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4228 - val_accuracy: 0.7922 - val_loss: 0.4553
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4224 - val_accuracy: 0.7857 - val_loss: 0.4549
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4225 - val_accuracy: 0.7857 - val_loss: 0.4557
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4222 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4216 - val_accuracy: 0.7857 - val_loss: 0.4545
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4212 - val_accuracy: 0.7857 - val_loss: 0.4546
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4209 - val_accuracy: 0.7857 - val_loss: 0.4555
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4211 - val_accuracy: 0.7857 - val_loss: 0.4554
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4204 - val_accuracy: 0.7857 - val_loss: 0.4551
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4204 - val_accuracy: 0.7857 - val_loss: 0.4547
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4200 - val_accuracy: 0.7857 - val_loss: 0.4535
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4192 - val_accuracy: 0.7857 - val_loss: 0.4537
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4193 - val_accuracy: 0.7857 - val_loss: 0.4536
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4190 - val_accuracy: 0.7857 - val_loss: 0.4535
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4186 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4181 - val_accuracy: 0.7857 - val_loss: 0.4536
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4179 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4180 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4175 - val_accuracy: 0.7857 - val_loss: 0.4530
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4172 - val_accuracy: 0.7857 - val_loss: 0.4529
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4171 - val_accuracy: 0.7857 - val_loss: 0.4527
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4164 - val_accuracy: 0.7857 - val_loss: 0.4524
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4162 - val_accuracy: 0.7857 - val_loss: 0.4518
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4157 - val_accuracy: 0.7857 - val_loss: 0.4523
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4159 - val_accuracy: 0.7857 - val_loss: 0.4522
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4152 - val_accuracy: 0.7857 - val_loss: 0.4520
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4148 - val_accuracy: 0.7857 - val_loss: 0.4522
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4147 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4145 - val_accuracy: 0.7857 - val_loss: 0.4523
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4139 - val_accuracy: 0.7857 - val_loss: 0.4527
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4137 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4137 - val_accuracy: 0.7857 - val_loss: 0.4537
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.4138 - val_accuracy: 0.7857 - val_loss: 0.4528
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4129 - val_accuracy: 0.7857 - val_loss: 0.4525
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.4128 - val_accuracy: 0.7857 - val_loss: 0.4520
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4122 - val_accuracy: 0.7857 - val_loss: 0.4520
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.4121 - val_accuracy: 0.7857 - val_loss: 0.4519
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4126 - val_accuracy: 0.7857 - val_loss: 0.4530
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4120 - val_accuracy: 0.7792 - val_loss: 0.4541
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8257 - loss: 0.4112 - val_accuracy: 0.7792 - val_loss: 0.4531
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.4113 - val_accuracy: 0.7792 - val_loss: 0.4527
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8241 - loss: 0.4108 - val_accuracy: 0.7792 - val_loss: 0.4524
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.4105 - val_accuracy: 0.7792 - val_loss: 0.4528
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.4103 - val_accuracy: 0.7792 - val_loss: 0.4530
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4101 - val_accuracy: 0.7857 - val_loss: 0.4519
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4095 - val_accuracy: 0.7792 - val_loss: 0.4518
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4093 - val_accuracy: 0.7792 - val_loss: 0.4518
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4089 - val_accuracy: 0.7792 - val_loss: 0.4524
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8225 - loss: 0.4089 - val_accuracy: 0.7792 - val_loss: 0.4520
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4086 - val_accuracy: 0.7792 - val_loss: 0.4519
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4082 - val_accuracy: 0.7857 - val_loss: 0.4510
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4077 - val_accuracy: 0.7792 - val_loss: 0.4510
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4076 - val_accuracy: 0.7792 - val_loss: 0.4513
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4071 - val_accuracy: 0.7792 - val_loss: 0.4513
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4069 - val_accuracy: 0.7792 - val_loss: 0.4507
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.4072 - val_accuracy: 0.7792 - val_loss: 0.4515
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4073 - val_accuracy: 0.7792 - val_loss: 0.4501
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4065 - val_accuracy: 0.7792 - val_loss: 0.4508
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4064 - val_accuracy: 0.7857 - val_loss: 0.4513
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4058 - val_accuracy: 0.7857 - val_loss: 0.4516
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4054 - val_accuracy: 0.7857 - val_loss: 0.4507
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.4053 - val_accuracy: 0.7857 - val_loss: 0.4503
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.4048 - val_accuracy: 0.7792 - val_loss: 0.4508
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4046 - val_accuracy: 0.7792 - val_loss: 0.4515
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4045 - val_accuracy: 0.7792 - val_loss: 0.4515
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4047 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4043 - val_accuracy: 0.7792 - val_loss: 0.4506
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4042 - val_accuracy: 0.7857 - val_loss: 0.4505
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4035 - val_accuracy: 0.7792 - val_loss: 0.4507
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4037 - val_accuracy: 0.7857 - val_loss: 0.4496
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4030 - val_accuracy: 0.7792 - val_loss: 0.4493
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4032 - val_accuracy: 0.7792 - val_loss: 0.4497
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4026 - val_accuracy: 0.7857 - val_loss: 0.4500
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4025 - val_accuracy: 0.7857 - val_loss: 0.4498
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.4024 - val_accuracy: 0.7857 - val_loss: 0.4498
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4020 - val_accuracy: 0.7922 - val_loss: 0.4496
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4014 - val_accuracy: 0.7857 - val_loss: 0.4496
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4015 - val_accuracy: 0.7857 - val_loss: 0.4501
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4016 - val_accuracy: 0.7922 - val_loss: 0.4489
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.4007 - val_accuracy: 0.7792 - val_loss: 0.4495
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.4017 - val_accuracy: 0.7792 - val_loss: 0.4489
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8339 - loss: 0.4000 - val_accuracy: 0.7792 - val_loss: 0.4492
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3999 - val_accuracy: 0.7857 - val_loss: 0.4493
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3997 - val_accuracy: 0.7857 - val_loss: 0.4494
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3988 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3987 - val_accuracy: 0.7987 - val_loss: 0.4492
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3985 - val_accuracy: 0.7987 - val_loss: 0.4488
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3984 - val_accuracy: 0.7857 - val_loss: 0.4476
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3979 - val_accuracy: 0.7987 - val_loss: 0.4481
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3977 - val_accuracy: 0.7987 - val_loss: 0.4481
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3981 - val_accuracy: 0.7922 - val_loss: 0.4480
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3972 - val_accuracy: 0.7922 - val_loss: 0.4473
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3969 - val_accuracy: 0.7922 - val_loss: 0.4472
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3969 - val_accuracy: 0.7922 - val_loss: 0.4469
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3966 - val_accuracy: 0.7792 - val_loss: 0.4478
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3963 - val_accuracy: 0.7922 - val_loss: 0.4482
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3961 - val_accuracy: 0.7922 - val_loss: 0.4476
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3957 - val_accuracy: 0.7922 - val_loss: 0.4469
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3954 - val_accuracy: 0.7922 - val_loss: 0.4461
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3950 - val_accuracy: 0.7922 - val_loss: 0.4458
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3951 - val_accuracy: 0.7922 - val_loss: 0.4460
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3945 - val_accuracy: 0.7922 - val_loss: 0.4463
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3946 - val_accuracy: 0.7987 - val_loss: 0.4464
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8371 - loss: 0.3945 - val_accuracy: 0.7922 - val_loss: 0.4465
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.8388 - loss: 0.3938 - val_accuracy: 0.7987 - val_loss: 0.4455
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.8388 - loss: 0.3932 - val_accuracy: 0.7987 - val_loss: 0.4451
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8388 - loss: 0.3932 - val_accuracy: 0.7987 - val_loss: 0.4448
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8388 - loss: 0.3931 - val_accuracy: 0.7922 - val_loss: 0.4449
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3932 - val_accuracy: 0.7922 - val_loss: 0.4444
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3925 - val_accuracy: 0.7987 - val_loss: 0.4441
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8388 - loss: 0.3924 - val_accuracy: 0.8052 - val_loss: 0.4442
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3925 - val_accuracy: 0.8052 - val_loss: 0.4440
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3917 - val_accuracy: 0.7987 - val_loss: 0.4436
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.3917 - val_accuracy: 0.7987 - val_loss: 0.4442
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3912 - val_accuracy: 0.7922 - val_loss: 0.4439
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3912 - val_accuracy: 0.7987 - val_loss: 0.4440
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3910 - val_accuracy: 0.7922 - val_loss: 0.4435
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3904 - val_accuracy: 0.8052 - val_loss: 0.4434
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3900 - val_accuracy: 0.8052 - val_loss: 0.4432
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3899 - val_accuracy: 0.7987 - val_loss: 0.4428
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3900 - val_accuracy: 0.8052 - val_loss: 0.4441
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3892 - val_accuracy: 0.7987 - val_loss: 0.4434
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3890 - val_accuracy: 0.7922 - val_loss: 0.4430
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3894 - val_accuracy: 0.8052 - val_loss: 0.4436
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3890 - val_accuracy: 0.7922 - val_loss: 0.4425
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3883 - val_accuracy: 0.7987 - val_loss: 0.4443
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3878 - val_accuracy: 0.7987 - val_loss: 0.4439
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3880 - val_accuracy: 0.8052 - val_loss: 0.4434
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3879 - val_accuracy: 0.8052 - val_loss: 0.4426
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3877 - val_accuracy: 0.8052 - val_loss: 0.4427
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8436 - loss: 0.3872 - val_accuracy: 0.7922 - val_loss: 0.4420
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3869 - val_accuracy: 0.7857 - val_loss: 0.4408
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8436 - loss: 0.3870 - val_accuracy: 0.7922 - val_loss: 0.4415
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3864 - val_accuracy: 0.7922 - val_loss: 0.4420
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3860 - val_accuracy: 0.7987 - val_loss: 0.4426
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3858 - val_accuracy: 0.7922 - val_loss: 0.4425
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3861 - val_accuracy: 0.7987 - val_loss: 0.4421
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3854 - val_accuracy: 0.7857 - val_loss: 0.4426
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3850 - val_accuracy: 0.7922 - val_loss: 0.4428
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3853 - val_accuracy: 0.7922 - val_loss: 0.4428
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8404 - loss: 0.3847 - val_accuracy: 0.7922 - val_loss: 0.4431
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8436 - loss: 0.3840 - val_accuracy: 0.7857 - val_loss: 0.4421
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3842 - val_accuracy: 0.7857 - val_loss: 0.4425
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8436 - loss: 0.3841 - val_accuracy: 0.7857 - val_loss: 0.4415
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8436 - loss: 0.3841 - val_accuracy: 0.7857 - val_loss: 0.4412
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8404 - loss: 0.3843 - val_accuracy: 0.7857 - val_loss: 0.4421
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8469 - loss: 0.3835 - val_accuracy: 0.7922 - val_loss: 0.4411
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8502 - loss: 0.3839 - val_accuracy: 0.7857 - val_loss: 0.4418
Epoch 156/200